version: 2
jobs:
  test:
    docker:
      - image: circleci/php:8-cli
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y git zip
      - run: sudo docker-php-ext-install zip
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
      - run: ./bin/phpunit
  build:
    branches:
      only:
        - build
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t abeatrice/circle:$CIRCLE_BRANCH .
      - run: docker push abeatrice/circle:$CIRCLE_BRANCH
